import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: "/favicon/favicon.ico"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}
      <Toaster toastOptions={{ className: 'bg-[#F9F9F9]', }} />
      </body>
    </html>
  );
}
